import type { Metadata } from "next";
// adding jersey 10 font 
import { Geist, Geist_Mono, Jersey_10 } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jersey = Jersey_10({
  subsets: ["latin"],
  weight: "400", // jersey only has one weight 
  variable: "--font-jersey",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jersey.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
